:scrollbar:
:data-uri:
:toc2:
:imagesdir: images

= RHEL 8 New Container tools

== Description
This Show&Tell is aimed to share some of the most important concepts and features of the new technology adopted by RHEL 8 to manage and implement containers, using podman, buildah and skopeo.

Duration: 4h with 2 breaks

Audience: IT Managers, Architects and technical staff who operates Linux

:numbered:

== New Container Technology
In RHEL 8 the docker package is replaced by the Container Tools module, which consists of Podman, Buildah, Skopeo and several other tidbits. These tools are compatible with the OCI specifications which means they can find, run, build and share containers with other tools that target the OCI standards including Docker CE, Docker EE, Kata Containers, CRI-O, and other container engines, registries, and tools. You can build with Buildah, and run with CRI-O. You can copy images from an AWS container registry to a local Podman instance. The OCI standards offer greater flexibility and choice.

== Open Container Initiative
The Open Container Initiative (OCI) is a lightweight, open governance structure (project), formed under the auspices of the Linux Foundation, for the express purpose of creating open industry standards around container formats and runtime.

The OCI currently contains two specifications: the Runtime Specification (runtime-spec) and the Image Specification (image-spec). The Runtime Specification outlines how to run a “filesystem bundle” that is unpacked on disk. At a high-level an OCI implementation would download an OCI Image then unpack that image into an OCI Runtime filesystem bundle. At this point the OCI Runtime Bundle would be run by an OCI Runtime.

== What is a Container
A container is a standard unit of software that packages up code and all its dependencies so the application runs quickly and reliably from one computing environment to another. A Docker container image is a lightweight, standalone, executable package of software that includes everything needed to run an application: code, runtime, system tools, system libraries and settings.

Container images become containers at runtime and in the case of Docker containers - images become containers when they run on Docker Engine. Available for both Linux and Windows-based applications, containerized software will always run the same, regardless of the infrastructure. Containers isolate software from its environment and ensure that it works uniformly despite differences for instance between development and staging. ^(1)^

^(1)^ source: https://www.docker.com/resources/what-container

== Some Terminology

=== Container Image
An image is a file that can be pulled down form a repository server, then used locally as a mount point for a starting container.

=== Container Image Format
Is the format every container technology provider has defined to the image file. Nevertheless nowadays is more common to see this format pledged to to the format defined by the Open Container Initiative (OCI). Basically this format define the layers and the metadata inside the container image.

This OCI image format propose a container image comprised of tar files for each layer and a manifest in json format.

=== The Container Engine
Users usually emits requests such as pulling images, running containers, etc. This requests are accepted by a software called the container engine. The container engine, in RHEL 8, run the container from an image using runc, which is a, OCI compliant runtime.

=== Image layer

An image is made of one or several layers. Layers are connected together in a parent-child relationship, so each layer states the change between itself and the parent layer.

=== Tag

When an image builder creates a new repository, they will label the best image layer to use, and this label is called a tag. These tags can refer to versions of software in a repository. One of these tags, which is a special one, is "latest" that point outs to the latest version in a repository.

=== Repository

Repositories are made of layers and metadata that defines an image. Usually we refer to a repository as a container image.

When we specify a repository on the command line, the Container Engine is doing a search on the registry servers that are configured in its configuration files.

=== Container runtime

A container runtime is a software which is in charge of several actions and responsibilities:

* User input management
* Input over an API typically used by others
* Handling the metadata which will be passed to the container Container Runtime
* Using user input for overriding defaults
* Using defaults specified by the container image
* Getting the Container Images from the Registry Server
* Managing the container image for decompressing and expanding it on disk
* Preparing a mount point for the container
* Calling the Container Runtime

runc is the OCI compliant runtime most used by users and developers nowadays.

=== Namespace

Namespaces separate groups of repositories. The namespace is typically the username of the person sharing the image, but can also be a group name, or a logical name. For example, Red Hat uses the namespace to separate groups of repositories based on products listed on the Red Hat Federated Registry server.

=== Kernel Namespace

A kernel namespace is different from a namespace in which the former enables each container to have it’s own mount points, network interfaces, user identifiers, process identifiers, etc.

Typically, a regular Linux process is created using a version of exec() system call. When a container is created, the container engine makes the request to the kernel with a special system call called clone(), which in consequence creates the process ith its own virtual mount points, process ids, user ids, network interfaces, hostname, etc, benefiting the process isolation from the regular processes.

=== Container

A container is an instance of a container image comprised of standard Linux processes which are ussually created using clone() system call.

Red Hat Enterprise Linux implements Linux Containers using core technologies such as Control Groups (Cgroups) for Resource Management, Namespaces for Process Isolation, SELinux for Security, enabling secure multi-tenancy and reducing the potential for security exploits. All this is meant to provide you with an environment to producing and running enterprise-quality containers.

=== Container Host

A container host is an Operating System Instance in charge of running the processes that compose a container. This host could be a physical, an on premise virtual machine or a cloud virtual instance.

=== Registry Server

It is a server which stores repositories. Usually when the repository is not locally cached, it can be pulled from different registries. For example Red Hat Enterprise Linux is configured to pull repositories from registry.access.redhat.com first, then it will try docker.io (Docker Hub) and quay.io.

=== Orchestration

The orchestration comes into the scene when scalability and control is necessary in a consistent way. What a container orchestration does is:

* Schedules container workloads into a cluster dynamically.
* Defines standard file formats for maintaining all metadata.

The capabilities that are obtained by an orchestration system could be the following.

* Consistency
* Automation
* Assistance on flowcharts otherwise manual

Red Hat Openshift is a good example of a container orchestration.

== New Tools for this era

=== What is Podman?

Podman is an open-source project that is available on most Linux platforms and resides on GitHub. It is a daemonless container engine for developing, managing, and running Open Container Initiative (OCI) containers and container images on your Linux System. Podman provides a Docker-compatible command line front end that can simply alias the Docker cli, `alias docker=podman`.

In Red Hat Enterprise Linux exists a way to mimic the docker cli installing podman-docker package, which gives Docker's administrators the look and feel of Docker command line.

Containers under the control of Podman can either be run by root or by a non-privileged user. Podman manages the entire container ecosystem which includes pods, containers, container images, and container volumes using the libpod library. Podman specializes in all of the commands and functions that help you to maintain and modify OCI container images, such as pulling and tagging. It allows you to create, run, and maintain those containers created from those images in a production environment.

source: https://podman.io/whatis.html

=== What is Buildah?

Buildah is a command-line tool for building Open Container Initiative-compatible images quickly and easily. It can act as a drop-in replacement for the Docker daemon’s docker build command but is flexible enough to allow you to build images with whatever tools you prefer to use. Buildah is easy to incorporate into scripts and build pipelines, and best of all, it doesn’t require a running container daemon to build its image.

Podman can be used to build containers, so what is the difference wirth Buildah?.

Podman uses Buildah’s build functionality under the covers to create a container image, but the two projects have differences. The most important difference between Podman and Buildah is their concept of a container. Podman allows users to create traditional containers and the intent of these containers is to be controlled through the entirety of a container life cycle. Buildah containers, on the other hand, are really created to allow content to be added to the container image. Each project has a separate internal representation of a container that is not shared. Because of this you cannot see Podman containers from within Buildah or vice versa. However the internal representation of a container image is the same between Buildah and Podman. In consequence, any container image that has been created, pulled or modified by one can be seen and used by the other.

source: https://opensource.com/article/18/6/getting-started-buildah

=== What is Skopeo?

Skopeo is a command line utility that performs various operations on container images and image repositories. it Can work with OCI images as well as the original Docker v2 images.

Skopeo works with API V2 registries such as Docker registries, the Atomic registry, private registries, local directories and local OCI-layout directories. Skopeo does not require a daemon to be running to perform these operations which consist of:

* Copying an image from and to various storage mechanisms. For example you can copy images from one registry to another, without requiring privilege.

* Inspecting a remote image showing its properties including its layers, without requiring you to pull the image to the host.

* Deleting an image from an image repository.

* When required by the repository, skopeo can pass the appropriate credentials and certificates for authentication.

source: https://github.com/containers/skopeo

== Let's get hands dirty

In this session we are going to do several activities related to the following workflow:

=== Going with the basics

* Understand how Podman works in general

*Install RHEL 8 container tools module*

[source,bash]
-----------------
# yum module install container-tools -y
-----------------

* Playing around with containers

*Configure Registries*

You can configure which and the order of the rgistries to be consulted in a search procedure with podman.

[source,bash]
-----------------
# more /etc/containers/registries.conf

# This is a system-wide configuration file used to
# keep track of registries for various container backends.
# It adheres to TOML format and does not support recursive
# lists of registries.

# The default location for this configuration file is /etc/containers/registries.conf.

# The only valid categories are: 'registries.search', 'registries.insecure',
# and 'registries.block'.

[registries.search]
registries = ['registry.redhat.io', 'registry.access.redhat.com', 'quay.io', 'docker.io']

...
-----------------

registries.conf, by default, has configures redhat, quay and then docker, which also is the order fo searching.

In the case of redhat 

*Install podman-docker package*

podman-docker is a package for letting Docker users to use docker command as they where working on a docker server. Installin the package is very easy and give docker administrator a comman ground for their admin stuff.

[source,bash]
-----------------
# yum install podman-docker -y

# docker info
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.2-6.module+el8.1.0+4830+f49150d7.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.1-dev, commit: unknown'
  Distribution:
    distribution: '"rhel"'
    version: "8.1"
  MemFree: 137306112
  MemTotal: 1028866048
  OCIRuntime:
    package: runc-1.0.0-61.rc8.module+el8.1.0+4873+4a24e241.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 1681203200
  SwapTotal: 1719660544
  arch: amd64
  cpus: 2
  hostname: showtellrhel
  kernel: 4.18.0-147.3.1.el8_1.x86_64
  os: linux
  rootless: false
  uptime: 1h 51m 40.29s (Approximately 0.04 days)
registries:
  blocked: null
  insecure: null
  search:
  - registry.redhat.io
  - registry.access.redhat.com
  - quay.io
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 7
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 5
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes

-----------------

We have issued a "docker info" command to inspect our containers environment installation. The output shows several pieces of important information such as versions, storage facilities, images stored, registries, etc.

*Search for registries*

The info parameter of podman command give us come useful information including the registries where, by default, the enginde look for images.

  search:
  - registry.redhat.io
  - registry.access.redhat.com
  - quay.io
  - docker.io
  

Let's search forthe ubi image of RHEL 8.

[source,bash]
-----------------
# podman search ubi8 | grep  registry.access.redhat.com

redhat.com   registry.access.redhat.com/ubi8                       The Universal Base Image is designed and eng...   0
redhat.com   registry.access.redhat.com/openjdk/openjdk-11-rhel8   OpenJDK S2I image for Java Applications on U...   0
redhat.com   registry.access.redhat.com/openjdk/openjdk-8-rhel8    OpenJDK 1.8 Image for Java Applications base...   0
redhat.com   registry.access.redhat.com/ubi8/dotnet-21             .NET Core 2.1 SDK and Runtime on RHEL 8           0
redhat.com   registry.access.redhat.com/ubi8/dotnet-30             .NET Core 3.0 SDK and Runtime on RHEL 8           0
redhat.com   registry.access.redhat.com/ubi8/dotnet-30-runtime     .NET Core 3.0 runtime only on RHEL 8              0
redhat.com   registry.access.redhat.com/ubi8/go-toolset            Platform for building and running Go 1.11.5 ...   0
redhat.com   registry.access.redhat.com/ubi8/perl-526              Platform for building and running Perl 5.26 ...   0
redhat.com   registry.access.redhat.com/ubi8/python-36             Platform for building and running Python 3.6...   0
redhat.com   registry.access.redhat.com/ubi8/ruby-25               Platform for building and running Ruby 2.5 a...   0
redhat.com   registry.access.redhat.com/ubi8/nodejs-10             Platform for building and running Node.js 10...   0
redhat.com   registry.access.redhat.com/ubi8/nodejs-12             Platform for building and running Node.js 12...   0
redhat.com   registry.access.redhat.com/ubi8/php-72                Platform for building and running PHP 7.2 ap...   0
redhat.com   registry.access.redhat.com/ubi8/php-73                Platform for building and running PHP 7.3 ap...   0
redhat.com   registry.access.redhat.com/ubi8/python-27             Platform for building and running Python 2.7...   0
redhat.com   registry.access.redhat.com/ubi8/ruby-26               Platform for building and running Ruby 2.6 a...   0
redhat.com   registry.access.redhat.com/ubi8/s2i-core              Base image which allows using of source-to-i...   0
redhat.com   registry.access.redhat.com/ubi8/ubi                   Provides the latest release of the Red Hat U...   0
redhat.com   registry.access.redhat.com/ubi8/dotnet-21-runtime     Provides the latest release of Red Hat Enter...   0
redhat.com   registry.access.redhat.com/ubi8/s2i-base              Base image with essential libraries and tool...   0
redhat.com   registry.access.redhat.com/ubi8/ubi-init              Provides the latest release of the Red Hat U...   0
redhat.com   registry.access.redhat.com/ubi8/ubi-minimal           Provides the latest release of the Minimal R...   0
redhat.com   registry.access.redhat.com/ubi8-minimal               The Universal Base Image Minimal is a stripp...   0
redhat.com   registry.access.redhat.com/ubi8-init                  The Universal Base Image Init is designed to...   0
-----------------

*Pull the RHEL 8 ubi image for use it

[source,bash]
-----------------
# podman pull registry.access.redhat.com/ubi8/ubi
Trying to pull registry.access.redhat.com/ubi8/ubi...Getting image source signatures
Copying blob fd8daf2668d1 done
Copying blob cb3c77f9bdd8 done
Copying config 096cae65a2 done
Writing manifest to image destination
Storing signatures
096cae65a2078ff26b3a2f82b28685b6091e4e2823809d45aef68aa2316300c7

# podman images
REPOSITORY                            TAG      IMAGE ID       CREATED       SIZE
registry.access.redhat.com/ubi8/ubi   latest   096cae65a207   4 weeks ago   239 MB
-----------------

With this image we will going to build our own container with a chatbot application.

*Pull an image with an application installed ready to be used*

The final goal of a container is to service to people or other applications to compose a more robust or elaborated service.

For example, nextcloud is a nice Dropbox clone that can be used right out the box.

Let's search for nextcloud image on any of the registries defined in the configuration file.

[source,bash]
-----------------
# yum search nextcloud

INDEX       NAME                                                   DESCRIPTION                                       STARS   OFFICIAL   AUTOMATED
quay.io     quay.io/rootlogin/nextcloud                            # Nextcloud  Blazing fast image containing N...   0
quay.io     quay.io/crazymax/nextcloud                             **Moved to [DockerHub](https://hub.docker.co...   0
...
docker.io   docker.io/library/nextcloud                            A safe home for all your data                     1232    [OK]
docker.io   docker.io/linuxserver/nextcloud                        A Nextcloud container, brought to you by Lin...   193
docker.io   docker.io/wonderfall/nextcloud                         All-in-one alpine-based Nextcloud image.          79         
...
-----------------

The output has been truncated for simplicity. The nextcloud container was found on quay and docker registries. Let's pull the official docker image.

[source,bash]
-----------------
#podman pull docker.io/library/nextcloud
Trying to pull docker.io/library/nextcloud...Getting image source signatures
Copying blob 83d8859e9744 done
Copying blob 85cf4fc86478 done
Copying blob 8ec398bc0356 done
Copying blob 970dadf4ccb6 done
Copying blob d6b7434b63a2 done
Copying blob 8c04561117a4 done
Copying blob 814ae7711d3c done
Copying blob 4896fed78b6b done
Copying blob 9c3d824d0ad5 done
Copying blob 9e316fd5b3b3 done
Copying blob 578b40496c37 done
Copying blob 280386098458 done
Copying blob 11a7c8596b56 done
Copying blob 46017765526c done
Copying blob e74d71e9611d done
Copying blob 8d04e75769f6 done
Copying blob d71822075f1a done
Copying blob b5b721156f26 done
Copying blob c749306a7cbf done
Copying blob d41cc464d579 done
Copying blob 6561bcc8c65b done
Copying config 3cd599c50a done
Writing manifest to image destination
Storing signatures
3cd599c50aec3e6612bfea1fc91e32912a17ecdfb33780f7ceed096b8627c573
-----------------

*Inspect images installed on the host*

podman can assit you to inspect an image.

[source,bash]
-----------------
# podman inspect registry.access.redhat.com/ubi8/ubi
[
    {
        "Id": "096cae65a2078ff26b3a2f82b28685b6091e4e2823809d45aef68aa2316300c7",
        "Digest": "sha256:9e3ba956fab8788c71645d85a7ad21023a6ebc2b7e48eb2940e91b0904d47a94",
        "RepoTags": [
            "registry.access.redhat.com/ubi8/ubi:latest"
        ],
        "RepoDigests": [
            "registry.access.redhat.com/ubi8/ubi@sha256:9e3ba956fab8788c71645d85a7ad21023a6ebc2b7e48eb2940e91b0904d47a94"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2019-12-10T17:54:10.824568Z",
        "Config": {
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "container=oci"
            ],
            "Cmd": [
                "/bin/bash"
            ],
            "Labels": {
                "architecture": "x86_64",
                "authoritative-source-url": "registry.access.redhat.com",
                "build-date": "2019-12-10T17:53:44.032126",
                "com.redhat.build-host": "cpt-1004.osbs.prod.upshift.rdu2.redhat.com",
                "com.redhat.component": "ubi8-container",
                "com.redhat.license_terms": "https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI",
                "description": "The Universal Base Image is designed and engineered to be the base layer for all of your containerized applications, middleware and utilities. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly.",
                "distribution-scope": "public",
                "io.k8s.description": "The Universal Base Image is designed and engineered to be the base layer for all of your containerized applications, middleware and utilities. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly.",
                "io.k8s.display-name": "Red Hat Universal Base Image 8",
                "io.openshift.expose-services": "",
                "io.openshift.tags": "base rhel8",
                "maintainer": "Red Hat, Inc.",
                "name": "ubi8",
                "release": "328",
                "summary": "Provides the latest release of Red Hat Universal Base Image 8.",
                "url": "https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8/images/8.1-328",
                "vcs-ref": "c42933bcdbf9f1c232e981a5e40de257c3534c8e",
                "vcs-type": "git",
                "vendor": "Red Hat, Inc.",
                "version": "8.1"
            }
        },...
]
-----------------

We can see a lot of info useful for admin purposes. This image is for RHEL 8.1 and was created on 2019-12-10

*Run a container from that image*

Let's start the nextcloud container. In this case, this a container with an application giving a service. Our container will be run starting all the modules and software required for service nextcloud, so we need to run this container in backgound.

[source,bash]
-----------------
# podman run --name=nextcloud -d -p 8080:80 docker.io/library/nextcloud
a26221d2aba4338206a7a7d5b51ccdd76f9eb9e51e6332e7667e127d908071a4

#podman ps
CONTAINER ID  IMAGE                               COMMAND               CREATED         STATUS             PORTS                 NAMES
a26221d2aba4  docker.io/library/nextcloud:latest  /entrypoint.sh ap...  20 seconds ago  Up 19 seconds ago  0.0.0.0:8080->80/tcp  nextcloud
-----------------

Let's see if the service is up and running?

[source,bash]
-----------------
# curl http://192.168.56.116:8080
<!DOCTYPE html>
<html class="ng-csp" data-placeholder-focus="false" lang="en" data-locale="en" >
        <head
 data-requesttoken="O5MhATiYUvPIj5vuTFzrXcfnBKrWIuYTHAABMzIMwAk=:DcFrOXDLCpyb/9SXdWWCDPSqceLuaqxJT3JAAQZbmEA=">
                <meta charset="utf-8">
                <title>
                Nextcloud               </title>
                <meta http-equiv="X-UA-Compatible" content="IE=edge">
                <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
                                <meta name="apple-itunes-app" content="app-id=1125420102">
                                <meta name="theme-color" content="#0082c9">
                <link rel="icon" href="/core/img/favicon.ico">
                <link rel="apple-touch-icon" href="/core/img/favicon-touch.png">
                <link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#0082c9">
                <link rel="manifest" href="/core/img/manifest.json">
                <link rel="stylesheet" href="/core/css/guest.css?v=ba222ded25d957b900c03bef914333cd">
                <script nonce="TzVNaEFUaVlVdlBJajV2dVRGenJYY2ZuQktyV0l1WVRIQUFCTXpJTXdBaz06RGNGck9YRExDcHliLzlTWGRXV0NEUFNxY2VMdWFxeEpUM0pBQVFaYm1FQT0=" defer src="/core/js/dist/main.js?v=ba222ded25d957b900c03bef914333cd"></script>
<script nonce="TzVNaEFUaVlVdlBJajV2dVRGenJYY2ZuQktyV0l1WVRIQUFCTXpJTXdBaz06RGNGck9YRExDcHliLzlTWGRXV0NEUFNxY2VMdWFxeEpUM0pBQVFaYm1FQT0=" defer src="/core/js/mimetype.js?v=ba222ded25d957b900c03bef914333cd"></script>
<script nonce="TzVNaEFUaVlVdlBJajV2dVRGenJYY2ZuQktyV0l1WVRIQUFCTXpJTXdBaz06RGNGck9YRExDcHliLzlTWGRXV0NEUFNxY2VMdWFxeEpUM0pBQVFaYm1FQT0=" defer src="/core/js/mimetypelist.js?v=ba222ded25d957b900c03bef914333cd"></script>
<script nonce="TzVNaEFUaVlVdlBJajV2dVRGenJYY2ZuQktyV0l1WVRIQUFCTXpJTXdBaz06RGNGck9YRExDcHliLzlTWGRXV0NEUFNxY2VMdWFxeEpUM0pBQVFaYm1FQT0=" defer src="/core/js/select2-toggleselect.js?v=ba222ded25d957b900c03bef914333cd"></script>
<script nonce="TzVNaEFUaVlVdlBJajV2dVRGenJYY2ZuQktyV0l1WVRIQUFCTXpJTXdBaz06RGNGck9YRExDcHliLzlTWGRXV0NEUFNxY2VMdWFxeEpUM0pBQVFaYm1FQT0=" defer src="/core/search/js/search.js?v=ba222ded25d957b900c03bef914333cd"></script>
<script nonce="TzVNaEFUaVlVdlBJajV2dVRGenJYY2ZuQktyV0l1WVRIQUFCTXpJTXdBaz06RGNGck9YRExDcHliLzlTWGRXV0NEUFNxY2VMdWFxeEpUM0pBQVFaYm1FQT0=" defer src="/core/js/setup.js?v=ba222ded25d957b900c03bef914333cd"></script>
<script nonce="TzVNaEFUaVlVdlBJajV2dVRGenJYY2ZuQktyV0l1WVRIQUFCTXpJTXdBaz06RGNGck9YRExDcHliLzlTWGRXV0NEUFNxY2VMdWFxeEpUM0pBQVFaYm1FQT0=" defer src="/core/search/js/searchprovider.js?v=ba222ded25d957b900c03bef914333cd"></script>
<script nonce="TzVNaEFUaVlVdlBJajV2dVRGenJYY2ZuQktyV0l1WVRIQUFCTXpJTXdBaz06RGNGck9YRExDcHliLzlTWGRXV0NEUFNxY2VMdWFxeEpUM0pBQVFaYm1FQT0=" defer src="/core/js/files/fileinfo.js?v=ba222ded25d957b900c03bef914333cd"></script>
<script nonce="TzVNaEFUaVlVdlBJajV2dVRGenJYY2ZuQktyV0l1WVRIQUFCTXpJTXdBaz06RGNGck9YRExDcHliLzlTWGRXV0NEUFNxY2VMdWFxeEpUM0pBQVFaYm1FQT0=" defer src="/core/js/files/client.js?v=ba222ded25d957b900c03bef914333cd"></script>
<script nonce="TzVNaEFUaVlVdlBJajV2dVRGenJYY2ZuQktyV0l1WVRIQUFCTXpJTXdBaz06RGNGck9YRExDcHliLzlTWGRXV0NEUFNxY2VMdWFxeEpUM0pBQVFaYm1FQT0=" defer src="/core/js/installation.js?v=ba222ded25d957b900c03bef914333cd"></script>
                        </head>
        <body id="body-login">
                <noscript>
        <div id="nojavascript">
                <div>
                        This application requires JavaScript for correct operation. Please <a href="https://www.enable-javascript.com/" target="_blank" rel="noreferrer noopener">enable JavaScript</a> and reload the page.          </div>
        </div>
</noscript>
                                <div class="wrapper">
...
        <p class="info">
                <span class="icon-info-white"></span>
                Need help?              <a target="_blank" rel="noreferrer noopener" href="https://docs.nextcloud.com/server/17/go.php?to=admin-install">See the documentation ↗</a>
        </p>
</form>
                                </main>
                        </div>
                </div>
                <footer role="contentinfo">
                        <p class="info">
                                <a href="https://nextcloud.com" target="_blank" rel="noreferrer noopener">Nextcloud</a> – a safe home for all your data      </p>
                </footer>
        </body>
</html>
-----------------

To access the nextcloud service simply open a brower and type http://192.168-56.x:8080

In this case, the service is a web service. In case you have other king of protocol you must need to undersdtanding first to access such service. This is going to be covered later.

Let's run the RHE 8 ubi container.

[source,bash]
-----------------
# podman run -ti registry.access.redhat.com/ubi8/ubi:latest /bin/bash

[root@8295cb3cba6b /]# yum update
Updating Subscription Management repositories.
Unable to read consumer identity
Subscription Manager is operating in container mode.
Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)                                                                      2.6 MB/s |  14 MB     00:05
Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)                                                                         3.1 MB/s |  13 MB     00:04
Red Hat Universal Base Image 8 (RPMs) - BaseOS                                                                                419 kB/s | 760 kB     00:01
Red Hat Universal Base Image 8 (RPMs) - AppStream                                                                             829 kB/s | 3.1 MB     00:03
Red Hat Universal Base Image 8 (RPMs) - CodeReady Builder                                                                     8.3 kB/s | 9.1 kB     00:01
Last metadata expiration check: 0:00:01 ago on Thu Jan  9 21:00:31 2020.
Dependencies resolved.
==============================================================================================================================================================
 Package                           Architecture               Version                              Repository                                            Size
==============================================================================================================================================================
Upgrading:
 gdb-gdbserver                     x86_64                     8.2-6.el8_0                          rhel-8-for-x86_64-appstream-rpms                     435 k
 setup                             noarch                     2.12.2-2.el8_1.1                     rhel-8-for-x86_64-baseos-rpms                        180 k

Transaction Summary
==============================================================================================================================================================
Upgrade  2 Packages

Total download size: 615 k
Is this ok [y/N]: y
Downloading Packages:
(1/2): gdb-gdbserver-8.2-6.el8_0.x86_64.rpm                                                                                   519 kB/s | 435 kB     00:00
(2/2): setup-2.12.2-2.el8_1.1.noarch.rpm                                                                                      210 kB/s | 180 kB     00:00
--------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                         715 kB/s | 615 kB     00:00
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                      1/1
  Upgrading        : setup-2.12.2-2.el8_1.1.noarch                                                                                                        1/4
warning: /etc/shadow created as /etc/shadow.rpmnew

  Running scriptlet: setup-2.12.2-2.el8_1.1.noarch                                                                                                        1/4
  Upgrading        : gdb-gdbserver-8.2-6.el8_0.x86_64                                                                                                     2/4
  Cleanup          : setup-2.12.2-2.el8_0.1.noarch                                                                                                        3/4
  Cleanup          : gdb-gdbserver-8.2-6.el8.x86_64                                                                                                       4/4
  Running scriptlet: gdb-gdbserver-8.2-6.el8.x86_64                                                                                                       4/4
  Verifying        : gdb-gdbserver-8.2-6.el8_0.x86_64                                                                                                     1/4
  Verifying        : gdb-gdbserver-8.2-6.el8.x86_64                                                                                                       2/4
  Verifying        : setup-2.12.2-2.el8_1.1.noarch                                                                                                        3/4
  Verifying        : setup-2.12.2-2.el8_0.1.noarch                                                                                                        4/4
Installed products updated.

Upgraded:
  gdb-gdbserver-8.2-6.el8_0.x86_64                                                setup-2.12.2-2.el8_1.1.noarch

Complete!
-----------------

[NOTE] 
Pood run execute the bash shell and with -ti set an interactive session where we can interact with the operating system as if we were on the host itself. In this case we executed a yum update.


- running rootless

=== Container building

* Create a Dockerfile file
- Choose the base
- Update and install packages and libraries need by the service is going to be installed in the image
- Copy the source code to the image
- Define the start command to run the service once the container is started


=== Running and testing the container

*List the local images*
*Run the container from the local image*
*Test the service*
*Backup the image*

[source,bash]
-----------------
# podman save -o ubi8_latest.tar registry.access.redhat.com/ubi8/ubi
 
# ls -lh

total 228M
-rw-r--r--. 1 root root 228M Jan  9 12:13 ubi8_latest.tar

-----------------

=== WebConsole to manage containers with Podman

* Installing the cockpit-podman plugin
* Managing a container lifecycle inside webconsole

== Resources and beyond

Sources

*
*
*
*
*
*
*
*
