:scrollbar:
:data-uri:
:toc2:
:imagesdir: images

:numbered:

== Description
This Show&Tell is aimed to share some of the most important concepts and features of the new technology adopted by RHEL 8 to manage and implement containers, using podman, buildah and skopeo. 

Duration: 4h with 2 breaks

Audience: IT Managers, Architects and technical staff who operates Linux

== New Container Technology
In RHEL 8 the docker package is replaced by the Container Tools module, which consists of Podman, Buildah, Skopeo and several other tidbits. These tools are compatible with the OCI specifications which means they can find, run, build and share containers with other tools that target the OCI standards including Docker CE, Docker EE, Kata Containers, CRI-O, and other container engines, registries, and tools. You can build with Buildah, and run with CRI-O. You can copy images from an AWS container registry to a local Podman instance. The OCI standards offer greater flexibility and choice.

== Open Container Initiative
The Open Container Initiative (OCI) is a lightweight, open governance structure (project), formed under the auspices of the Linux Foundation, for the express purpose of creating open industry standards around container formats and runtime. 

The OCI currently contains two specifications: the Runtime Specification (runtime-spec) and the Image Specification (image-spec). The Runtime Specification outlines how to run a “filesystem bundle” that is unpacked on disk. At a high-level an OCI implementation would download an OCI Image then unpack that image into an OCI Runtime filesystem bundle. At this point the OCI Runtime Bundle would be run by an OCI Runtime.

== What is a Container
A container is a standard unit of software that packages up code and all its dependencies so the application runs quickly and reliably from one computing environment to another. A Docker container image is a lightweight, standalone, executable package of software that includes everything needed to run an application: code, runtime, system tools, system libraries and settings.

Container images become containers at runtime and in the case of Docker containers - images become containers when they run on Docker Engine. Available for both Linux and Windows-based applications, containerized software will always run the same, regardless of the infrastructure. Containers isolate software from its environment and ensure that it works uniformly despite differences for instance between development and staging. ^(1)^

^(1)^ source: https://www.docker.com/resources/what-container

== Some Terminology

=== Container Image
An image is a file that can be pulled down form a repository server, then used locally as a mount point for a starting container.

=== Container Image Format
Is the format every container technology provider has defined to the image file. Nevertheless nowadays is more common to see this format pledged to to the format defined by the Open Container Innitiative (OCI). Basically this format define the layers and the metadata inside the container image.

This OCI image format propose a container image comprised of tar files for each layer and a manifest in json format.

=== The Container Engine

== Architecture
== New Tools for this era
=== What is podman?
==== Common Ground
==== Using podman on RHEL

= What is Buildah?
==== Common Ground
==== Using buildah on RHEL

== What is Skopeo
==== Common Ground
==== Using skopeo on RHEL

== WebConsole (cockpit) with containers
=== Installing the cockpit-podman plugin
=== Managing a container lifecycle inside webconsole

== Resources and beyond
