:scrollbar:
:data-uri:
:toc2:
:imagesdir: images

= Upgrading RHEL 7 to 8 with LEAPP and BOOM - LTO Show & Tell Series

== Description
This Show&Tell is aimed to share some of the most important concepts and actions needed for upgrading a RHEL 7 to RHEL 8.

Audience: IT Managers, Architects, IT security specialists and technical staff who operates Linux

:numbered:

== Introduction

This Show & Tell is intended to give system administrators information about leapp as a tool for assiting in the upgrading fromn RHEL 7 to RHEL 8 instances, with the minimal effort but with maximum security and a very short downtime window.

== Understand the environment and evaluate the pre-requisites.

An in-place upgrade is a recommended and supported way for migrating your system to the next major version of RHEL. This applies to RHEL 6 to RHEL 7 or RHEL 7 to RHEL 8 instances.

=== Applications

We need to understand, at first, the environment in terms of the applications installed. This is a very important step, mainly because after the upgrading process some packages and libraries will be depracated or changed in versions. Applications need to be analyzed under the light of what thay use of the operating system to run properly. Leapp pre-upgrade report is a good source of this kind of information, allowing the possibility to match the running application requierements with the possible changes the OS will experiment. In case of changes impacting the application, we need to take actions on this, that could go from modifying the application to install a new version of it.

=== Operating system and HW considerations.

Take a look of the https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/upgrading_from_rhel_7_to_rhel_8/index#planning-an-upgrade_upgrading-from-rhel-7-to-rhel-8[requierements] needed to be considered for prepare the environment for the upgrading.

== Preparing a RHEL 7 system for the upgrade

=== Check instance is subscribed

Ensure the system is registered, if not you can use subscription-manager to do so.

[source,bash]
-----------------------------------------
subscription-manager register --auto-attach
-----------------------------------------

=== Check the current version and release of the running instance.

[source,bash]
-----------------------------------------
subscription-manager list --installed
+-------------------------------------------+
    Installed Product Status
+-------------------------------------------+
Product Name:   Red Hat Enterprise Linux Server
Product ID:     69
Version:        7.8
Arch:           x86_64
Status:         Not Subscribed
Status Details:
Starts:
Ends:
-----------------------------------------

In this example the version is 7.8 which is the last minor version of RHEL 7, at the moment this article was writen. In case we are not in the last minor version, we need to update the RHEL instance appropiately.

In some cases customers lock the updates to a specific versions. In this case we need to instruct the Subscription Manager to consume the latest content.

[source,bash]
-----------------------------------------
subscription-manager release --unset
yum versionlock clear
-----------------------------------------

=== Add the proper repositories

[source,bash]
-----------------------------------------
subscription-manager repos --enable rhel-7-server-rpms -enable rhel-7-server-extras-rpms
-----------------------------------------

=== Update the instance

Run yum to update the instance to the lasted update.

[source,bash]
-----------------------------------------
yum update
-----------------------------------------

=== Install LEAPP utility

Leapp is an OS and application modernization framework. In this case leapp is used for upgrading the OS from RHEL 7 to RHEL 8.

[source,bash]
-----------------------------------------
yum install leapp leapp-repository
-----------------------------------------

At this point we need to download additional required data files attached to the Knowledgebase https://access.redhat.com/articles/3664871[article] Data required by the Leapp utility for an in-place upgrade from RHEL 7 to RHEL 8 and place them in the /etc/leapp/files/ directory. This is necessary for a successful upgrade. Note that currently you need data files from the *leapp-data8.tar.gz* archive or later.

*NOTE:* we need to download the file *leapp-data8.tar.gz* using a browser, then uncompress it on  /etc/leapp/files

[source,bash]
-----------------------------------------
tar -xzf leapp-data8.tar.gz -C /etc/leapp/files && rm leapp-data8.tar.gz
-----------------------------------------

=== GRUB Considerations

If GRUB is installed outside of the default location, which is /boot, export the respective environment variable as follows:

[source,bash]
-----------------------------------------
export LEAPP_GRUB_DEVICE="/path_to_device"
-----------------------------------------

=== Automated tools considerations

Ensure you have any configuration management (such as Salt, Chef, Puppet, Ansible) disabled or adequately reconfigured to not attempt to restore the original RHEL 7 system.

=== Network Considerations

Ensure your system does not use more than one Network Interface Card (NIC) with a name based on the prefix used by the kernel *(eth)*.

=== Backup & Recovery Considerations

Ensure you have a full system backup or a virtual machine snapshot. you can use the https://access.redhat.com/solutions/2115051[Relax-and-Recover (ReaR) utility]. Alternatively, you can use https://www.redhat.com/en/blog/upgrading-rhel-7-rhel-8-leapp-and-boom[LVM snapshots using Boom], or RAID splitting.
