:scrollbar:
:data-uri:
:toc2:
:imagesdir: images

= RED HAT INSIGHTS: UNDERSTANDING WHAT'S INSIDE - LTO Show & Tell Series

== Description
This Show&Tell is aimed to share some of the most important concepts and features of Insights and hiow it can help to customer looking for stability, availability, security and performance in their Operating System Grid.

Audience: IT Managers, Architects and technical staff who operates Linux

:numbered:

== Introduction
As existing workloads evolve and deployments grow in size and complexity, risk management is a key challenge for enterprise IT. To succeed, operations departments need to rapidly deploy new environments and ensure systems scale reliably. Red Hat® Insights helps customers benefit from the experience and technical knowledge of Red Hat Certified Engineers (RHCEs®) and makes it easier for users to identify, prioritize, and resolve issues before business operations are affected.

Red Hat Insights provides highly scalable, prescriptive analytics across complete, hybrid infrastructures. Red Hat Insights is also now included in all supported versions of Red Hat Enterprise Linux®, enabling users to proactively detect issues, enhance visibility into their deployments, improve security, and prescribe remediation through familiar tools like Red Hat Satellite.

Delivered as a Software-as-a-Service (SaaS) offering, Red Hat Insights takes advantage of Red Hat’s industry expertise as a leader in open source software to generate tailored remediations in real time.

Red Hat Insights uses intelligent data to pinpoint technical risks and help IT resolve problems before business is affected. This modern, integrated platform supports operational analytics and automated resolution across physical, virtual, container, and private and public cloud environments.

== How to install the client

The client for RHEL 8 is installed by default. In case other version (version>=6.4) the installation is pretty straightforward.

Before any installation you need to register the server with the appropriate subscription, which has to be active.

[source,bash]
---------------------
[root@server ~]# subscription-manager register --auto-attach
---------------------

The installation of the client is as follows . Remember to register the server to insights after the rpm installation.

*RHEL version < 8*

[source,bash]
---------------------
[root@server ~]# yum install redhat-access-insights
[root@server ~]#  redhat-access-insights --register
Automatic scheduling for Insights has been enabled.
Starting to collect Insights data for archimedes
Uploading Insights data.
Successfully uploaded report from archimedes to account xxxxxxxx.
---------------------

*RHEL version 8*

[source,bash]
---------------------
[root@server ~]# yum install insights-client
[root@server ~]#  insights-clients --register
Automatic scheduling for Insights has been enabled.
Starting to collect Insights data for archimedes
Uploading Insights data.
Successfully uploaded report from archimedes to account xxxxxxxx.
---------------------

The automated versions can be located at ansible or puppet links.

Is good practice to configure the servers you want to subscribe to insights through a proxy, so the server aren't exposed directly to a public connection. 

== What does insights client when it is registering the server?

The client starts a protocol to get the server registered looking at the subscription validity. If the subscription is valid and up to date, the server is registered.

The client try to register the instance through port 443 on

[source,bash]
---------------------
https://cert-api.access.redhat.com/r/insights/uploads
---------------------

After a successful registration, the client creates an autonomous task for uploading data daily. 

In RHEL versions 7.4 and below versions, it uses cron and creates an entry in /etc/cron.daily.

I RHEL versions 7.5 and above, it uses a timer in systemd that can be changed using

[source,bash]
---------------------
[root@server ~]# systemctl edit insights-client.timer
The file can be found at /usr/lib/systemd/system/.
---------------------

Please refer to “Creating Custom Schedule for Red Hat Insights Uploads”.

In big environments is desirable not to make all servers upload data at the same time. For this reason there is a random delay time variable called RandomizedDelaySec that can be changed in the timer file to resolve the bulk uploads that can impact the network.

After the configuration of a scheduled task, insights client start the first data collection which is sent to insights service right away.

After this, the registration process finish. The next upload will happen automatically daily and the service is set permanently. The data uploaded can be seen at the service portal.

== What data is sent to Red Hat Insights service?

The data collected by insights could be reviewed and validated using --no-upload keyword as follows.

[source,bash]
---------------------
[root@server ~]# insights-client --no-upload
Starting to collect Insights data for server
Archive saved at /var/tmp/h517f24d/insights-server-20190923155120.tar.gz
---------------------

In this example a compressed file is stored in a random generated folder in /var/tmp. The files collected are configuration files and the output of different commands that are sent to the service for analysis and recommendations.

You can also refer to “System Information Collected by Red Hat Insights”

Also you can refer to the information depicted in the uploader.json from the insights api.

== Can I exclude data?

The information sent to the insights service is related mostly to the server configuration. Nevertheless, some customers could have the need of not sending all the information, that by default, insights collect.

In this case, customers could decide to trim the information collected or obfuscate hostnames and/or ip addresses as needed.

For obfuscating hostname and/or ip address, edit the file 

[source,bash]
---------------------
/etc/insights-client/insights-client.conf 
---------------------

Uncomment the following lines and set to True.

[source,bash]
---------------------
# Obfuscate IP addresses
#obfuscate=False

# Obfuscate hostname. Requires obfuscate=True.
#obfuscate_hostname=False
---------------------

[NOTE]
Obfuscating IP addresses and host names will cause difficulties in identifying systems in the Insights UI. For instance, host0 will be displayed for all systems if host names are obfuscated. When registering systems to Red Hat Insights be sure to use the --display-name option to set a UI name to avoid this issue.

[source,bash]
---------------------
# Display name for registration
#display_name=
---------------------

The Red Hat Insights collection agent has the ability to exclude (blacklist) entire files, specific commands, specific patterns, and specific keywords from the data that is sent to Red Hat.

To enable these exclusions, you must create a file called */etc/insights-client/remove.conf* and specify this file in the remove_file line of */etc/insights-client/insights-client.conf*, as in the following example:

[source,bash]
---------------------
remove_file=/etc/insights-client/remove.conf
---------------------

An example of a remove.conf file is below.

[source,bash]
---------------------
[remove]
files=/etc/cluster/cluster.conf,/etc/hosts
commands=/bin/dmesg
patterns=password,username
---------------------

See the detailed procedure in *“Opting Out of Sending Metadata from Red Hat Insights Client”*.

Any omission of metadata will impact any analysis related to the data avoided.
 
== Force to upload data to Insights Service

When you apply remediation steps to your servers could be useful to refresh the information of servers touched by the procedures implemented. This could be done using the client without parameters.

[source,bash]
---------------------
[root@server ~]# insights-client
Starting to collect Insights data for server
Uploading Insights data.
Successfully uploaded report from archimedes to account xxxxxxxxx.
---------------------

== Unregistering a server

A server can be unregistered using the command line. 

[source,bash]
---------------------
[root@server ~]# insights-client --unregister
Successfully unregistered from the Red Hat Insights Service
---------------------

== Integrating Insights with others: using the API with python

Insights expose a powerful API in order to interact with the service.

A good article to start with is “Managing the Insights API”

Using python for interacting with python is very fun and easy.

A very simple class for listing the servers and IDs registered to insights.

[source,bash]
---------------------
import json
import sys
from pprint import pprint

try:
    import requests
except ImportError:
    print("Please install the python-requests module.")
    sys.exit(-1)

SSL_VERIFY = True

###############################################                
class InsightsRequest:

	def __init__(self):
		self.data = None
		self.rules=None
		self.credentials = loadCredentials()
	#------------------------
	def fetchHostsInfo(self):
		r = requests.get(
"https://cloud.redhat.com/api/inventory/v1/hosts",
			auth=(self.credentials["username"], self.credentials["password"]),
			verify=SSL_VERIFY,
			params="")
		self.data = r.json()
		return r.json()

	#------------------------
	def getHostsInfo(self):
		return self.data

	#------------------------
	def getRegisteredHostsDisplayNames(self):
		returnValue = []
		if self.data != None:
			for host in self.data["results"]: returnValue.append(host["display_name"])
	
	#------------------------
	def getRegisteredHostsIds(self):
		returnValue = []
		if self.data != None:
			for host in self.data["results"]: returnValue.append([host["display_name"],host["id"]])		
		return returnValue
		
###############################################                
def loadCredentials():
	
	# ~ The format of credentials.txt must be
	# ~ {
		# ~ "username":"your username",
		# ~ "password":"your password"
	# ~ }

	json_data = None
	with open('credentials.txt', 'r') as f:
		data = f.read()
		json_data = json.loads(data)
		
	return json_data
		
###############################################                
if __name__=='__main__':
#----------------------------------------------
	
	insightsData = InsightsRequest()
	
	insightsData.fetchHostsInfo()
	
	for serverId in insightsData.getRegisteredHostsIds(): 
       print(serverId)
---------------------

It is important to notice that these are demonstration scripts and commands. Ensure you review these scripts carefully before use, and replace any variable, user names, passwords, and other information to suit your own demonstration deployment.

== How to connect the servers to the service?

