:scrollbar:
:data-uri:
:toc2:
:imagesdir: images

= Securing Linux Servers and auditing security policies with OpenSCAP - LTO Show & Tell Series

== Description
This Show&Tell is aimed to share some of the most important concepts and features of OpenSCAP as a tool for auditing security policies.

Audience: IT Managers, Architects, IT security specialists and technical staff who operates Linux

:numbered:

== Introduction

== Need for Audting Security Poilicies

== What is OpenSCAP?

== Installing OpenSCAP

=== The OpenSCAP oscap command line utility

This utility enables us to scan systems validating security compliance content and generating reports and guides based on the scans and evaluations made. This is the front end to the OpenSCAP library and groups.

[source, bash]
------------------------
# yum install -y openscap-scanner

Updating Subscription Management repositories.
Last metadata expiration check: 0:01:45 ago on Tue 25 Feb 2020 03:18:32 PM EST.
Dependencies resolved.
===============================================================================================================================================
 Package                          Architecture           Version                        Repository                                        Size
===============================================================================================================================================
Installing:
 openscap-scanner                 x86_64                 1.3.1-1.el8                    rhel-8-for-x86_64-appstream-rpms                  66 k
Installing dependencies:
 openscap                         x86_64                 1.3.1-1.el8                    rhel-8-for-x86_64-appstream-rpms                 3.3 M

Transaction Summary
========================================================================================================================================
Install  2 Packages

Total download size: 3.4 M
Installed size: 58 M
Downloading Packages:
(1/2): openscap-scanner-1.3.1-1.el8.x86_64.rpm                                                                 100 kB/s |  66 kB     00:00
(2/2): openscap-1.3.1-1.el8.x86_64.rpm                                                                         4.4 MB/s | 3.3 MB     00:00
----------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                          4.5 MB/s | 3.4 MB     00:00
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                       1/1
  Installing       : openscap-1.3.1-1.el8.x86_64                                                                                           1/2
  Running scriptlet: openscap-1.3.1-1.el8.x86_64                                                                                           1/2
  Installing       : openscap-scanner-1.3.1-1.el8.x86_64                                                                                   2/2
  Running scriptlet: openscap-scanner-1.3.1-1.el8.x86_64                                                                                   2/2
  Verifying        : openscap-scanner-1.3.1-1.el8.x86_64                                                                                   1/2
  Verifying        : openscap-1.3.1-1.el8.x86_64                                                                                           2/2
Installed products updated.

Installed:
  openscap-scanner-1.3.1-1.el8.x86_64                                        openscap-1.3.1-1.el8.x86_64

Complete!
------------------------

=== The security guide for SCAP

Before we can start using oscap we need to install or import security content. For this excersice we can install the SCAP Security Guide (SSG) package that contains the currently most evolved and elaborated set of security polices for Linux systems

[source, bash]
---------------------------
# yum install scap-security-guide

Updating Subscription Management repositories.
Last metadata expiration check: 0:11:12 ago on Tue 25 Feb 2020 03:29:45 PM EST.
Dependencies resolved.
========================================================================================================================================
 Package                            Architecture          Version                        Repository                                       Size
========================================================================================================================================Installing:
 scap-security-guide                noarch                0.1.46-1.el8                   rhel-8-for-x86_64-appstream-rpms                6.6 M

Transaction Summary
========================================================================================================================================
Install  1 Package

Total download size: 6.6 M
Installed size: 173 M
Is this ok [y/N]: y
Downloading Packages:
scap-security-guide-0.1.46-1.el8.noarch.rpm                                                                    4.7 MB/s | 6.6 MB     00:01
----------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                          4.7 MB/s | 6.6 MB     00:01
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                       1/1
  Installing       : scap-security-guide-0.1.46-1.el8.noarch                                                                               1/1
  Running scriptlet: scap-security-guide-0.1.46-1.el8.noarch                                                                               1/1
  Verifying        : scap-security-guide-0.1.46-1.el8.noarch                                                                               1/1
Installed products updated.

Installed:
  scap-security-guide-0.1.46-1.el8.noarch

Complete!
---------------------------

After the installation SSG security content will be available in the following directory.

[source, bash]
--------------------------
 ls /usr/share/xml/scap/ssg/content/

ssg-firefox-cpe-dictionary.xml  ssg-jre-ds-1.2.xml            ssg-rhel6-ocil.xml            ssg-rhel7-xccdf.xml
ssg-firefox-cpe-oval.xml        ssg-jre-ds.xml                ssg-rhel6-oval.xml            ssg-rhel8-cpe-dictionary.xml
ssg-firefox-ds-1.2.xml          ssg-jre-ocil.xml              ssg-rhel6-xccdf.xml           ssg-rhel8-cpe-oval.xml
ssg-firefox-ds.xml              ssg-jre-oval.xml              ssg-rhel7-cpe-dictionary.xml  ssg-rhel8-ds-1.2.xml
ssg-firefox-ocil.xml            ssg-jre-xccdf.xml             ssg-rhel7-cpe-oval.xml        ssg-rhel8-ds.xml
ssg-firefox-oval.xml            ssg-rhel6-cpe-dictionary.xml  ssg-rhel7-ds-1.2.xml          ssg-rhel8-ocil.xml
ssg-firefox-xccdf.xml           ssg-rhel6-cpe-oval.xml        ssg-rhel7-ds.xml              ssg-rhel8-oval.xml
ssg-jre-cpe-dictionary.xml      ssg-rhel6-ds-1.2.xml          ssg-rhel7-ocil.xml            ssg-rhel8-xccdf.xml
ssg-jre-cpe-oval.xml            ssg-rhel6-ds.xml              ssg-rhel7-oval.xml
--------------------------


=== The OpenSCAP Base

=== The OpenSCAP Workbench


=== Purpose of XCCDF and OVAL Policies

=== Scanning the RHEL infrastructure with OSCAP

=== Running regular scans with OpenSCAP Daemon

=== Scanning the RHEL infrastructure with OpenSCAP Workbench

=== Interpreting the results

=== Automating OpenSCAP installation with Ansible

