:scrollbar:
:data-uri:
:toc2:
:imagesdir: images

= RED HAT INSIGHTS: AUTOMATING REMEDIATIONS & FIXES

== Description
This Show&Tell is aimed to share some of the most important concepts and features of Insights and how we can automate remediations and fixes needed to get the platform to be stable, secure and in compliance.

Audience: IT Managers, Architects and technical staff who operates Linux

:numbered:

== Introduction
As existing workloads evolve and deployments grow in size and complexity, risk management is a key challenge for enterprise IT. To succeed, operations departments need to rapidly deploy new environments and ensure systems scale reliably. Red Hat® Insights helps customers benefit from the experience and technical knowledge of Red Hat Certified Engineers (RHCEs®) and makes it easier for users to identify, prioritize, and resolve issues before business operations are affected.

Red Hat Insights provides highly scalable, prescriptive analytics across complete, hybrid infrastructures. Red Hat Insights is also now included in all supported versions of Red Hat Enterprise Linux®, enabling users to proactively detect issues, enhance visibility into their deployments, improve security, and prescribe remediation through familiar tools like Red Hat Satellite.

Delivered as a Software-as-a-Service (SaaS) offering, Red Hat Insights takes advantage of Red Hat’s industry expertise as a leader in open source software to generate tailored remediations in real time.

Red Hat Insights uses intelligent data to pinpoint technical risks and help IT resolve problems before business is affected. This modern, integrated platform supports operational analytics and automated resolution across physical, virtual, container, and private and public cloud environments.

In the management equation not only exists the identification phase, but the remediation of the identified issues. Insights is intellegint enough to propose manual remediations, including step-by-step cookbooks to revolve a state that is not convenient for our platform. Nevertheless, in what Insights excels is how this tool propose those remediations in the automation realm. 

Insights is capable to propose playbooks for each remediation and fix proposed, that can be gathered and composed into more complex and rich playbooks to address several issues and servers at the same time, gaining more control over what needs to be acomplished to bring the platform from a current state to a needed one, without the intervention of the command line, which is prone to errors that in consequence raise the risks.

This Show & Tell is aimed to show you how we can, with the help of Insights and Ansible, remediate issues or fix states using the proposed playbooks by Insights. We will be visiting some procedures for addressing recommendations, vulnerabilities and compliance, so we can have the peace of mind that our platform is treated with proved automated procedures.

== How to install the client

The client for RHEL 8 is installed by default. In case other version (version>=6.4) the installation is pretty straightforward.

Before any installation you need to register the server with the appropriate subscription, which has to be active.

[source,bash]
---------------------
[root@server ~]# subscription-manager register --auto-attach
---------------------

The installation of the client is as follows . Remember to register the server to insights after the rpm installation.

*RHEL version < 8*

[source,bash]
---------------------
[root@server ~]# yum install redhat-access-insights
[root@server ~]#  redhat-access-insights --register
Automatic scheduling for Insights has been enabled.
Starting to collect Insights data for archimedes
Uploading Insights data.
Successfully uploaded report from archimedes to account xxxxxxxx.
---------------------

*RHEL version 8*

[source,bash]
---------------------
[root@server ~]# yum install insights-client
[root@server ~]#  insights-clients --register
Automatic scheduling for Insights has been enabled.
Starting to collect Insights data for archimedes
Uploading Insights data.
Successfully uploaded report from archimedes to account xxxxxxxx.
---------------------

The automated versions can be located at ansible or puppet links.

Is good practice to configure the servers you want to subscribe to insights through a https://access.redhat.com/solutions/1606693[proxy], so the server aren't exposed directly to a public connection. 

== What does insights client when it is registering the server?

The client starts a protocol to get the server registered looking at the subscription validity. If the subscription is valid and up to date, the server is registered.

The client try to register the instance through port 443 on

[source,bash]
---------------------
https://cert-api.access.redhat.com/r/insights/uploads
---------------------

After a successful registration, the client creates an autonomous task for uploading data daily. 

In RHEL versions 7.4 and below versions, it uses cron and creates an entry in /etc/cron.daily.

I RHEL versions 7.5 and above, it uses a timer in systemd that can be changed using

[source,bash]
---------------------
[root@server ~]# systemctl edit insights-client.timer
The file can be found at /usr/lib/systemd/system/.
---------------------

In big environments is desirable not to make all servers upload data at the same time. For this reason there is a random delay time variable called RandomizedDelaySec that can be changed in the timer file to resolve the bulk uploads that can impact the network.

After the configuration of a scheduled task, insights client start the first data collection which is sent to insights service right away.

After this, the registration process finish. The next upload will happen automatically daily and the service is set permanently. The data uploaded can be seen at the service portal.




